"""Reusable diagnostic primitives.

Experiment-specific analyses are kept under :mod:`rl.scenarios.diagnostics`.
New scenarios should use :mod:`rl.diagnostics.io` and
:mod:`rl.diagnostics.reporting` for artifact boundaries.
"""

from .io import (
    atomic_write_bytes,
    atomic_write_text,
    canonical_json,
    canonical_json_bytes,
    canonical_jsonl_bytes,
    parse_json_bytes,
    parse_jsonl_bytes,
    read_json,
    read_jsonl,
    require_sha256,
    sha256_bytes,
    sha256_file,
    sha256_json,
    sha256_jsonl,
    sha256_text,
    verify_sha256,
    write_json,
    write_jsonl,
)
from .reporting import ArtifactRecord, ManifestBuilder, artifact_record, build_manifest, write_report
from .metrics import (
    auc,
    bootstrap_ci,
    cohens_d_pooled,
    distribution,
    exact_mcnemar_p,
    exact_sign_p,
    js_divergence_bits,
    mean,
    numeric_values,
    paired_delta_summary,
    percentile,
)
from .records import (
    actions,
    group_by_example_index,
    group_rows,
    index_rows,
    load_json,
    load_jsonl,
    only_sample,
    samples,
    selected_rows,
    trajectory_action_signature,
    trajectory_actions,
    turns,
)
from .replay import format_action, group_rollouts, local_error_statuses, read_rows, stable_action_digest
from .trajectory import (
    NEGATIVE_DENSE_CATEGORIES,
    POSITIVE_DENSE_CATEGORIES,
    dense_reward_category,
    is_negative_dense_category,
    is_positive_dense_category,
)
from .validation import (
    finite_number,
    regular_dir,
    regular_file,
    require,
    require_fields,
    task_id,
)

__all__ = [
    "ArtifactRecord",
    "ManifestBuilder",
    "artifact_record",
    "atomic_write_bytes",
    "atomic_write_text",
    "build_manifest",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_jsonl_bytes",
    "parse_json_bytes",
    "parse_jsonl_bytes",
    "read_json",
    "read_jsonl",
    "require_sha256",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "sha256_jsonl",
    "sha256_text",
    "verify_sha256",
    "write_json",
    "write_jsonl",
    "write_report",
    "auc",
    "bootstrap_ci",
    "cohens_d_pooled",
    "distribution",
    "exact_mcnemar_p",
    "exact_sign_p",
    "js_divergence_bits",
    "mean",
    "numeric_values",
    "paired_delta_summary",
    "percentile",
    "actions",
    "group_by_example_index",
    "group_rows",
    "index_rows",
    "load_json",
    "load_jsonl",
    "only_sample",
    "samples",
    "selected_rows",
    "trajectory_action_signature",
    "trajectory_actions",
    "turns",
    "group_rollouts",
    "format_action",
    "local_error_statuses",
    "read_rows",
    "stable_action_digest",
    "NEGATIVE_DENSE_CATEGORIES",
    "POSITIVE_DENSE_CATEGORIES",
    "dense_reward_category",
    "finite_number",
    "is_negative_dense_category",
    "is_positive_dense_category",
    "regular_dir",
    "regular_file",
    "require",
    "require_fields",
    "task_id",
]
